name: deploy-docs

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  meta:
    uses: ./.github/workflows/meta.yml

  build:
    needs: meta
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.meta.outputs.tag }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: tools/Doxygen/Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-gen/html
          publish_branch: gh-pages
          commit_message: ${{ needs.meta.outputs.tag }}
